### ISSUE TITLE
About Test-time optimization of position estimation

### ISSUE THREAD

**Issue by PraveenKumar-Rajendran** [yolish/camera-pose-auto-encoders-raw#1]
Hi, @yolish !
Thanks for the nice work! :)

Could you please provide the final version of the file "main_refine_guess_test_time.py" ?
As it differs from the paper. 

Thank you! :)
Looking forward to your reply.

**Comment by yolish** [comment]
Hi, Praveen - thank you for your interest in our work! This script corresponds to one of suppl. tables in the paper. Please note that we are planning to re-create this repo with a more user friendly README as well as new results for RPR with PAE (which in my opinion is the main application of RPR). It will a bit of time due to low availability but should be ready soon.
